# Generated by Django 6.0.3 on 2026-03-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('receptionist', 'Recepção'), ('doctor', 'Médico'), ('enfermagem', 'Enfermagem'), ('farmacia', 'Farmácia'), ('financeiro', 'Financeiro'), ('painel', 'Painel')], max_length=20)),
                ('permission_slug', models.CharField(max_length=50)),
                ('is_granted', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('role', 'permission_slug')},
            },
        ),
    ]
