# Generated by Django 6.0.3 on 2026-03-17 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Convênio')),
                ('registro_ans', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registro ANS')),
                ('tipo', models.CharField(default='convenio', max_length=100, verbose_name='Tipo')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': 'Convênios',
                'db_table': 'convenios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConvenioProcedimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_tuss', models.CharField(max_length=20, verbose_name='Código TUSS')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição TUSS')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='convenios.convenio')),
            ],
            options={
                'verbose_name': 'Procedimento do Convênio',
                'verbose_name_plural': 'Procedimentos do Convênio',
                'db_table': 'convenio_procedimentos',
                'ordering': ['codigo_tuss'],
            },
        ),
    ]
