version: '3.8'

services:
  # Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: medtrace_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-clinica_db}
      POSTGRES_USER: ${DB_USER:-clinica_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-clinica_pass}
    ports:
      - "${DB_HOST_PORT:-5440}:5432"
    volumes:
      - medtrace_db_data:/var/lib/postgresql/data
    networks:
      - medtrace_network

  # Backend Django
  backend:
    build: .
    container_name: medtrace_api
    restart: always
    environment:
      - DATABASE_URL=postgres://${DB_USER:-clinica_user}:${DB_PASSWORD:-clinica_pass}@db:5432/${DB_NAME:-clinica_db}
      - DJANGO_DEBUG=False
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-django-insecure-prod-key}
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - medtrace_network

  # Frontend React
  frontend:
    build: ./frontend
    container_name: medtrace_ui
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - medtrace_network

networks:
  medtrace_network:
    driver: bridge

volumes:
  medtrace_db_data:
