# Generated by Django 6.0.3 on 2026-03-09 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_appointment_attendance_finished_at_and_more'),
        ('patients', '0003_delete_medicalrecord'),
        ('professionals', '0002_alter_professional_crm_alter_professional_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('chief_complaint', models.TextField(blank=True, null=True, verbose_name='Queixa Principal')),
                ('clinical_evolution', models.TextField(blank=True, null=True, verbose_name='Evolução Clínica')),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Diagnóstico (CID)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações Livres')),
                ('atestado_dias', models.IntegerField(blank=True, null=True, verbose_name='Dias de Afastamento')),
                ('atestado_inicio', models.DateField(blank=True, null=True, verbose_name='Início do Afastamento')),
                ('atestado_retorno', models.DateField(blank=True, null=True, verbose_name='Retorno')),
                ('atestado_observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Atestado')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='patients.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='records', to='professionals.professional')),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=255, verbose_name='Medicamento')),
                ('dose', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dose')),
                ('frequency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Frequência')),
                ('duration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Duração')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prescriptions', to='professionals.professional')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
