# Generated by Django 6.0.3 on 2026-03-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Medicamento')),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('provider', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fornecedor')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['name'],
            },
        ),
    ]
