# Generated by Django 6.0.3 on 2026-03-09 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade Movimentada')),
                ('type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste'), ('vencimento', 'Vencimento')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição/Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='medications.medication')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação de Medicamento',
                'verbose_name_plural': 'Movimentações de Medicamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
