# Generated by Django 6.0.3 on 2026-03-18 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_alter_professional_crm_alter_professional_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.IntegerField(default=30)),
                ('active', models.BooleanField(default=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='professionals.professional')),
            ],
            options={
                'unique_together': {('professional', 'day_of_week')},
            },
        ),
    ]
