# Generated by Django 6.0.3 on 2026-03-09 01:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0002_patient_address_patient_email_and_more'),
        ('professionals', '0002_alter_professional_crm_alter_professional_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'appointment_time'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(db_index=True, default=datetime.date(2026, 3, 9)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(1, 9, 4, 525826)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='attendance_number',
            field=models.IntegerField(blank=True, help_text='Número da senha/fila de atendimento', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 9, 1, 9, 16, 377415, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_encaixe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='professionals.professional'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.CharField(blank=True, help_text='Consultório/Sala', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('aguardando', 'Aguardando'), ('triagem', 'Triagem'), ('em_atendimento', 'Em Atendimento'), ('atendido', 'Atendido'), ('faltou', 'Faltou'), ('cancelado', 'Cancelado')], db_index=True, default='agendado', max_length=20),
        ),
    ]
