# Generated by Django 6.0.3 on 2026-03-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_remove_appointment_doctor_and_more'),
        ('patients', '0002_patient_address_patient_email_and_more'),
        ('professionals', '0002_alter_professional_crm_alter_professional_email_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_encaixe', False), models.Q(('status__in', ['cancelado', 'faltou']), _negated=True)), fields=('professional', 'appointment_date', 'appointment_time'), name='unique_active_appointment_no_encaixe'),
        ),
    ]
