# Generated by Django 6.0.3 on 2026-03-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_unique_active_appointment_no_encaixe'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attendance_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim do Atendimento'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='attendance_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início do Atendimento'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_encaixe',
            field=models.BooleanField(default=False, verbose_name='É Encaixe?'),
        ),
    ]
