# Generated by Django 6.0.3 on 2026-03-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_attendance_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('aguardando', 'Aguardando'), ('triagem', 'Triagem'), ('chamado', 'Chamado'), ('em_atendimento', 'Em Atendimento'), ('atendido', 'Atendido'), ('faltou', 'Faltou'), ('cancelado', 'Cancelado')], db_index=True, default='agendado', max_length=20),
        ),
    ]
