# Generated by Django 6.0.3 on 2026-03-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_panelcall_scheduleblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleblock',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
