# Generated by Django 6.0.3 on 2026-03-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_scheduleblock_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='authorization_number',
            field=models.CharField(blank=True, help_text='Número de Autorização', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guia_number',
            field=models.CharField(blank=True, help_text='Número da Guia TISS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='procedimento_tuss',
            field=models.CharField(blank=True, help_text='Código/Descrição TUSS', max_length=255, null=True),
        ),
    ]
