# Generated by Django 6.0.3 on 2026-03-18 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0008_appointment_authorization_number_and_more'),
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('enviado', 'Enviado')], db_index=True, default='aberto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_lots', to='convenios.convenio')),
            ],
            options={
                'verbose_name': 'Lote de Faturamento',
                'verbose_name_plural': 'Lotes de Faturamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_conciliacao', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('glosa', 'Glosa'), ('recurso', 'Recurso')], db_index=True, default='pendente', max_length=20)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_item', to='appointments.appointment')),
                ('billing_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='faturamento.billinglot')),
            ],
            options={
                'verbose_name': 'Item de Faturamento',
                'verbose_name_plural': 'Itens de Faturamento',
                'ordering': ['id'],
            },
        ),
    ]
