# Generated by Django 6.0.3 on 2026-03-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_delete_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
