# Generated by Django 6.0.3 on 2026-03-18 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0001_initial'),
        ('patients', '0004_patient_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='convenios.convenio'),
        ),
        migrations.AddField(
            model_name='patient',
            name='numero_carteirinha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tipo_plano',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='validade_plano',
            field=models.DateField(blank=True, null=True),
        ),
    ]
