# Generated by Django 6.0.3 on 2026-03-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Chave')),
                ('value', models.TextField(verbose_name='Valor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Sistema',
                'verbose_name_plural': 'Configurações de Sistema',
            },
        ),
    ]
